# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, you will have to restart the server process.

title: Jekyll Template
baseurl: "/jekyll-template"  # with leading slash, without trailing slash; should be the name of the repo is serving on GitHub Pages; use the empty string (""), not a slash, if you host on a custom domain
url: https://mattisg.github.io  # no trailing slash
repository: MattiSG/jekyll-template
description: A template for websites rather than blogs.
lang: en  # set the language of your website with its ISO code in order to improve indexation and automated translation
# twitter_username: MattiSG  # associate a Twitter username with this website

collections:
  toplevel:
    output: true
defaults:  # rather than repeating config in all YAML front matters, use defaults for each type of content you have in your website
  -
    scope:
      path: "" # means "all files"
    values:
      layout: default
  -
    scope:
      path: toplevel # targets a collection
    values:
      layout: default

exclude:
  - .circleci
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
