# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, you will have to restart the server process.

title: Jekyll Template
baseurl: ""
url: https://jekylltemplate.example
lang: en  # set the language of your website here with its ISO code in order to expose it in the HTML and improve indexation and automated translation

defaults:  # rather than repeating config in all YAML front matters, use defaults for each type of content you have in your website
  -
    scope:
      path: "" # means "all files"
    values:
      layout: default

include: ['_pages']  # avoid mixing content files with config & dev files: all files under `_pages` get their URL set with `permalink`

exclude:
  - .circleci
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
